### PR TITLE
bootstrap on the sign up page + added a button

### PR DESCRIPTION
**Pull request by JulieMariano**
I added bootstrap on the sign up page + added a btn button
sign up

### CODE REVIEW

**Comment by LaureOlivier** [comment]
Hi Julie, can you change the color of the button to the brown color of the palette : #9D2503 ?

**Comment by JulieMariano** [comment]
Hey :D ! Of course, so should I also changed it on the login page so we have consistency on both  :) ?

**Comment by LaureOlivier** [comment]
yes! nice!

**Comment by JulieMariano** [comment]
Better like this :) ? Will do the sign in right after !

sign up update

**Pull request merged**
